sudo: required
dist: trusty
language: cpp
cache:
  - apt
  - brew

os:
  - linux
  - osx

env:
  - QT=qt57


before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
         export DISPLAY=:99.0;
         sh -e /etc/init.d/xvfb start;
    fi

install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
         sudo apt-get -qq update;
         sudo apt-get -qq install libssl-dev pkg-config libxcb-util0-dev;
         if [[ "$QT" == "qt57" ]]; then sudo apt-add-repository -y ppa:beineri/opt-qt57-trusty; sudo apt-get update -qq; sudo apt-get install -qq ${QT}tools ${QT}script ${QT}webengine ${QT}webchannel ${QT}declarative ${QT}x11extras; fi
    fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
         brew update;
         brew install openssl;
         brew install qt5;
    fi

script:
  - QMAKE="qmake"
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
         CXXFLAGS="-Wextra -Werror";
         QMAKE="/opt/${QT}/bin/qmake";
    fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
         CXXFLAGS="-Wextra -Werror -Wno-inconsistent-missing-override -Wno-deprecated-declarations";
         QMAKE=/usr/local/opt/qt5/bin/qmake;
    fi
  - $QMAKE QMAKE_CXXFLAGS+="$CXXFLAGS"
  - make || exit 1
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
         ./mac/macdeploy.sh;
         cd bin;
         ls -l;
         cp -v libQupZilla*.dylib tests/autotests;
    fi
  - cd scripts && ./run_tests.sh $QMAKE
